name: Build & Deploy Dev

env:
  USER: "${{vars.DEV_USERNAME}}"
  PASSWORD: "${{secrets.DEV_PASSWORD}}"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        default: dev
        description: Deploy to env
        options:
          - dev

      branch:
        type: choice
        required: true
        default: develop
        description: Deploy from branch
        options:
          - develop

jobs:
  Build:
    environment: dev
    runs-on: windows-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          repository: "indugamers/${{github.event.repository.name}}"

      - name: Setup MSBUILD
        uses: microsoft/setup-msbuild@v1.1

      - name: setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore ConsoleApp.sln

      - name: Display credentials
        run: |
          echo Environment selected : ${{github.event.inputs.env}}

      - name: Build
        run: msbuild ConsoleApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ github.workspace }}\ConsoleApp\ConsoleApp\bin\Release\net6.0\ /p:PrecompileBeforePublish=true /p:EnableUpdateable=false

      - name: Generate Build Artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: "Publish-Artifacts"
          path: ${{github.workspace}}\ConsoleApp\bin\Release\net6.0

      - name: Display Artifacts
        run: |
          echo Artifacts at runner location = ${{github.workspace}}\ConsoleApp\bin\Release\net6.0
          cd ${{github.workspace}}\ConsoleApp\bin\Release\net6.0
          dir
