name: Build & Deploy Dev

env:
  USER: "${{vars.DEV_USERNAME}}"
  PASSWORD: "${{secrets.DEV_PASSWORD}}"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        default: dev
        description: Deploy to env
        options:
          - dev

      branch:
        type: choice
        required: true
        default: develop
        description: Deploy from branch
        options:
          - dev

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup MSBUILD
        uses: microsoft/setup-msbuild@v1.1

      - name: setup NuGet
        uses: nuget/setup-nuget@v1

      # - name: Restore NuGet packages
      #   run: nuget restore ConsoleApp.sln

      - name: Display credentials
        run: |
          echo Environment selected : ${{github.event.inputs.env}}
          echo "$USER"
          echo "$env.PASSWORD"

      - name: Display credentials1
        run: echo $USER

      - name: Display credentials2
        run: echo $env.PASSWORD
